<?php echo "<?php\n";

if( $this->namespace )
{
    echo 'namespace ' . $this->namespace . ';';
}
?>


/**
 * Value Object class
 *
 * Generated by <?php echo get_class( $this ) ?>.
 *
<?php

/* @var $column \Sql\Reflection\Column */
foreach( $this->tableReflection->columns as $column )
{
    echo ' * @property-read mixed ', $column->name, PHP_EOL;
}
?>
 */
class <?php echo $this->getClassName(); ?> extends \Erum\ModelAbstract
{

    const table = '<?php echo ( $this->tableReflection->schema ? $this->tableReflection->schema . '.' : '' ) , $this->tableReflection->name ?>';
<?php

/* @var $column \Sql\Reflection\Column */
foreach( $this->tableReflection->columns as $column )
{
    ?>

    /**
     * @sql-type <?php echo strtolower( $column->datatype ), PHP_EOL; ?>
     */
    <?php echo 'protected $' , $column->name , ';' , PHP_EOL;
}
?>
    
    /**
     * Serialized table reflection object
     * 
     * @var string
     */
    private static $_reflectionSerialized = '<?php echo serialize( $this->tableReflection ); ?>';
    
    /**
     * Table reflection object
     *
     * @var \Sql\Reflection\Table
     */
    private static $_reflection;
      
    /**
     *
     * @return \Sql\Reflection\Table
     */
    public function tableReflection()
    {
        if( null === self::$_reflection )
        {
            self::$_reflection = unserialize( self::$_reflectionSerialized );
        }
        
        return self::$_reflection;
    }
}
